# Generated by Django 6.0.6 on 2026-06-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('WASTED', 'Wasted')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('PANTRY', 'Pantry'), ('FRIDGE', 'Fridge'), ('FREEZER', 'Freezer'), ('MEDICINE', 'Medicine')], max_length=20),
        ),
    ]
