# Generated by Django 6.0.6 on 2026-06-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesuggestion',
            name='prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
