name: Django Tests

on:
  push:
    branches:
      - main
      - feat/**

  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        env:
          SECRET_KEY: test-secret
          DEBUG: True
          DB_NAME: test
          DB_USER: test
          DB_PASSWORD: test
          DB_HOST: localhost
          DB_PORT: 5432
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_KEY: test-key
        run: |
          pytest